languaje: python
python: 
  - "3.8.10"
services: mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
cache: pip
install: "pip install -r requirements.txt"
script: python testApi.py